enabled: true

processClusterStore: true
processClusterExternalSecret: false
processPushSecret: false

image:
  repository: ghcr.io/external-secrets/external-secrets
  tag: "v0.10.5"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: external-secrets

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
