apiVersion: v1
kind: Namespace
metadata:
  name: acmecorp
  labels:
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    app.kubernetes.io/managed-by: Helm
