{{- if .Values.namespaces.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "acmecorp-platform.namespace.app" . }}
  labels:
    app.kubernetes.io/managed-by: Helm
    acmecorp.io/namespace-role: application
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "acmecorp-platform.namespace.observability" . }}
  labels:
    app.kubernetes.io/managed-by: Helm
    acmecorp.io/namespace-role: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "acmecorp-platform.namespace.externalSecrets" . }}
  labels:
    app.kubernetes.io/managed-by: Helm
    acmecorp.io/namespace-role: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "acmecorp-platform.namespace.data" . }}
  labels:
    app.kubernetes.io/managed-by: Helm
    acmecorp.io/namespace-role: data
{{- end }}
