FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /project

COPY pom.xml ./pom.xml
COPY src ./src

RUN mvn -DskipTests package

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /project/target/quarkus-app/ ./quarkus-app/

EXPOSE 8080

CMD ["java", "-jar", "/app/quarkus-app/quarkus-run.jar"]
