apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalog-service.fullname" . }}-config
  namespace: {{ include "acmecorp-platform.namespace.app" . }}
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}
data:
  QUARKUS_DATASOURCE_JDBC_URL: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.global.aurora.host .Values.global.aurora.port .Values.global.aurora.database | quote }}
  QUARKUS_DATASOURCE_USERNAME: {{ .Values.config.username | quote }}
