apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "billing-service.fullname" . }}-config
  labels:
    {{- include "billing-service.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.global.aurora.host | quote }}
  DB_PORT: {{ .Values.global.aurora.port | quote }}
  DB_NAME: {{ .Values.global.aurora.database | quote }}
  MQ_HOST: {{ .Values.global.mq.host | quote }}
  MQ_PORT: {{ .Values.global.mq.port | quote }}
