{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "billing-service.fullname" . }}
  namespace: {{ include "acmecorp-platform.namespace.observability" . }}
  labels:
    {{- include "billing-service.labels" . | nindent 4 }}
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - {{ include "acmecorp-platform.namespace.app" . }}
  selector:
    matchLabels:
      {{- include "billing-service.labels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
      path: /actuator/prometheus
{{- end }}
