#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${TF_DIR:-$ROOT_DIR/infra/terraform}"
CHART_DIR="${CHART_DIR:-$ROOT_DIR/helm/acmecorp-platform}"
WEBAPP_DIR="${WEBAPP_DIR:-$ROOT_DIR/webapp}"
TF_VARS_FILE="${TF_VARS_FILE:-terraform.tfvars}"
PUBLIC_HOSTED_ZONE_NAME="${PUBLIC_HOSTED_ZONE_NAME:-acmecorp.autoscaling.io}"
GATEWAY_INGRESS_HOST="${GATEWAY_INGRESS_HOST:-api.${PUBLIC_HOSTED_ZONE_NAME}}"
GRAFANA_INGRESS_HOST="${GRAFANA_INGRESS_HOST:-grafana.${PUBLIC_HOSTED_ZONE_NAME}}"
UI_SUBDOMAIN="${UI_SUBDOMAIN:-app}"
AWS_PROFILE="${AWS_PROFILE:-tf}"
AWS_REGION="${AWS_REGION:-eu-west-1}"
CLUSTER_NAME="${CLUSTER_NAME:-acmecorp-platform}"
HELM_RELEASE="${HELM_RELEASE:-acmecorp-platform}"
NAMESPACE_APP="${NAMESPACE_APP:-acmecorp}"
NAMESPACE_OBS="${NAMESPACE_OBS:-observability}"
NAMESPACE_DATA="${NAMESPACE_DATA:-data}"
NAMESPACE_EXTERNAL_SECRETS="${NAMESPACE_EXTERNAL_SECRETS:-external-secrets}"
AUTO_APPROVE="${AUTO_APPROVE:-false}"
SKIP_SSO_LOGIN="${SKIP_SSO_LOGIN:-false}"
SKIP_UI_DEPLOY="${SKIP_UI_DEPLOY:-false}"
SKIP_CLOUDFRONT_INVALIDATION="${SKIP_CLOUDFRONT_INVALIDATION:-false}"
ROLLOUT_TIMEOUT="${ROLLOUT_TIMEOUT:-600s}"
NODE_READY_TIMEOUT="${NODE_READY_TIMEOUT:-20m}"
INGRESS_TIMEOUT_SECONDS="${INGRESS_TIMEOUT_SECONDS:-900}"
PROD_VALUES_PATH="${PROD_VALUES_PATH:-/tmp/acmecorp-values-prod.generated.yaml}"
IMAGE_TAG="${IMAGE_TAG:-prod-$(date -u +%Y%m%d%H%M%S)}"

export AWS_PROFILE
export AWS_REGION
export TF_DIR
export TF_VARS_FILE
export RELEASE_NAME="$HELM_RELEASE"

log() {
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

section() {
  printf '\n[%s] ==> %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
}

die() {
  log "ERROR: $*"
  exit 1
}

on_error() {
  local exit_code="$1"
  local line_no="$2"
  log "ERROR: setup-prod.sh failed at line ${line_no} with exit code ${exit_code}."
  exit "$exit_code"
}

trap 'on_error $? $LINENO' ERR

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

require_file() {
  local path="$1"
  [[ -f "$path" ]] || die "required file not found: $path"
}

resolve_tf_vars_path() {
  if [[ "$TF_VARS_FILE" = /* ]]; then
    printf '%s\n' "$TF_VARS_FILE"
    return
  fi

  printf '%s\n' "$TF_DIR/$TF_VARS_FILE"
}

tf_apply_args=()
if [[ "$AUTO_APPROVE" == "true" ]]; then
  tf_apply_args+=(-auto-approve)
fi

warn_namespace_override_limitations() {
  if [[ "$NAMESPACE_APP" != "acmecorp" || "$NAMESPACE_OBS" != "observability" || "$NAMESPACE_DATA" != "data" || "$NAMESPACE_EXTERNAL_SECRETS" != "external-secrets" ]]; then
    log "WARNING: this chart still hardcodes some namespaces. Non-default namespace overrides are not fully supported by the current repo."
  fi
}

ensure_tooling() {
  section "Validate Local Tooling"
  require_cmd aws
  require_cmd curl
  require_cmd docker
  require_cmd helm
  require_cmd jq
  require_cmd kubectl
  require_cmd npm
  require_cmd terraform
  require_file "$ROOT_DIR/scripts/restore-secrets-if-pending-deletion.sh"
  require_file "$ROOT_DIR/scripts/build-and-push-ecr.sh"
  require_file "$ROOT_DIR/scripts/render-prod-values.sh"
  require_file "$ROOT_DIR/scripts/validate-deploy.sh"
  require_file "$ROOT_DIR/scripts/bootstrap-first-cluster.sh"
  require_file "$ROOT_DIR/scripts/finalize-alb-dns.sh"
  require_file "$ROOT_DIR/scripts/deploy-ui.sh"
  require_file "$CHART_DIR/values.yaml"
  require_file "$CHART_DIR/values-prod.yaml"
  require_file "$WEBAPP_DIR/package.json"
  log "Tooling and required repo scripts are present."
}

ensure_aws_session() {
  section "Check AWS Credentials"
  if aws sts get-caller-identity >/dev/null 2>&1; then
    log "AWS session is active for profile ${AWS_PROFILE}."
    return
  fi

  if [[ "$SKIP_SSO_LOGIN" == "true" ]]; then
    die "AWS credentials are not active and SKIP_SSO_LOGIN=true."
  fi

  log "AWS session is not active. Running aws sso login for profile ${AWS_PROFILE}."
  aws sso login --profile "$AWS_PROFILE"
  aws sts get-caller-identity >/dev/null 2>&1 || die "AWS credentials are still unavailable after aws sso login."
}

upsert_tfvar() {
  local file_path="$1"
  local key="$2"
  local rendered_value="$3"
  local tmp_file

  tmp_file="$(mktemp)"
  awk -v key="$key" -v value="$rendered_value" '
    BEGIN { replaced = 0 }
    $0 ~ "^[[:space:]]*" key "[[:space:]]*=" {
      if (!replaced) {
        print key " = " value
        replaced = 1
      }
      next
    }
    { print }
    END {
      if (!replaced) {
        print key " = " value
      }
    }
  ' "$file_path" >"$tmp_file"
  mv "$tmp_file" "$file_path"
}

ensure_tfvars() {
  local tf_vars_path="$1"

  section "Prepare Terraform Variables"
  mkdir -p "$(dirname "$tf_vars_path")"

  if [[ ! -f "$tf_vars_path" ]]; then
    cat >"$tf_vars_path" <<EOF
# Generated by scripts/setup-prod.sh for delegated-subdomain production deploys.
aws_region = "${AWS_REGION}"
cluster_name = "${CLUSTER_NAME}"
public_hosted_zone_name = "${PUBLIC_HOSTED_ZONE_NAME}"
gateway_ingress_host = "${GATEWAY_INGRESS_HOST}"
grafana_ingress_host = "${GRAFANA_INGRESS_HOST}"
ui_subdomain = "${UI_SUBDOMAIN}"
enable_grafana_dns = true
EOF
    log "Created Terraform vars file: $tf_vars_path"
    return
  fi

  upsert_tfvar "$tf_vars_path" "aws_region" "\"${AWS_REGION}\""
  upsert_tfvar "$tf_vars_path" "cluster_name" "\"${CLUSTER_NAME}\""
  upsert_tfvar "$tf_vars_path" "public_hosted_zone_name" "\"${PUBLIC_HOSTED_ZONE_NAME}\""
  upsert_tfvar "$tf_vars_path" "gateway_ingress_host" "\"${GATEWAY_INGRESS_HOST}\""
  upsert_tfvar "$tf_vars_path" "grafana_ingress_host" "\"${GRAFANA_INGRESS_HOST}\""
  upsert_tfvar "$tf_vars_path" "ui_subdomain" "\"${UI_SUBDOMAIN}\""
  upsert_tfvar "$tf_vars_path" "enable_grafana_dns" "true"
  log "Ensured delegated-zone settings are present in $tf_vars_path"
}

run_terraform_apply() {
  local tf_vars_path="$1"

  section "Terraform Init And Apply"
  terraform -chdir="$TF_DIR" init
  terraform -chdir="$TF_DIR" apply -input=false "${tf_apply_args[@]}" -var-file="$tf_vars_path"
}

update_kubeconfig() {
  section "Update Kubeconfig"
  aws eks update-kubeconfig --region "$AWS_REGION" --name "$CLUSTER_NAME" >/dev/null
  log "Updated kubeconfig for cluster ${CLUSTER_NAME}."
}

wait_for_cluster() {
  section "Wait For EKS Cluster"
  aws eks wait cluster-active --region "$AWS_REGION" --name "$CLUSTER_NAME"

  local attempt
  for attempt in {1..60}; do
    if kubectl cluster-info >/dev/null 2>&1; then
      break
    fi
    sleep 10
  done

  kubectl cluster-info >/dev/null 2>&1 || die "kubectl could not reach the EKS cluster."
  kubectl wait --for=condition=Ready node --all --timeout="$NODE_READY_TIMEOUT"
  log "Cluster is reachable and all nodes are Ready."
}

bootstrap_cluster() {
  section "Bootstrap First Cluster"
  ROLLOUT_TIMEOUT="$ROLLOUT_TIMEOUT" RELEASE_NAME="$HELM_RELEASE" "$ROOT_DIR/scripts/bootstrap-first-cluster.sh"
}

build_and_push_images() {
  section "Build And Push Backend Images"
  IMAGE_TAG="$IMAGE_TAG" AWS_REGION="$AWS_REGION" "$ROOT_DIR/scripts/build-and-push-ecr.sh" "$IMAGE_TAG"
}

render_prod_values() {
  section "Render Production Helm Values"
  IMAGE_TAG="$IMAGE_TAG" AWS_REGION="$AWS_REGION" "$ROOT_DIR/scripts/render-prod-values.sh" "$PROD_VALUES_PATH" "$IMAGE_TAG"
  [[ -f "$PROD_VALUES_PATH" ]] || die "rendered production values file was not created: $PROD_VALUES_PATH"
  log "Rendered values file: $PROD_VALUES_PATH"
}

validate_deploy_inputs() {
  section "Validate Deployment Inputs"
  PROD_VALUES="$PROD_VALUES_PATH" IMAGE_TAG="$IMAGE_TAG" RELEASE_NAME="$HELM_RELEASE" TF_VARS_FILE="$TF_VARS_FILE" "$ROOT_DIR/scripts/validate-deploy.sh"
}

install_or_upgrade_release() {
  section "Install Or Upgrade Helm Release"
  helm dependency update "$CHART_DIR"
  helm upgrade --install "$HELM_RELEASE" "$CHART_DIR" \
    --namespace "$NAMESPACE_APP" \
    --create-namespace \
    -f "$CHART_DIR/values.yaml" \
    -f "$PROD_VALUES_PATH"
}

wait_for_rollout() {
  local kind="$1"
  local name="$2"
  local namespace="$3"
  kubectl rollout status "${kind}/${name}" -n "$namespace" --timeout="$ROLLOUT_TIMEOUT"
}

wait_for_workloads() {
  section "Wait For Workloads"
  wait_for_rollout deployment external-secrets "$NAMESPACE_EXTERNAL_SECRETS"
  wait_for_rollout deployment "${HELM_RELEASE}-gateway-service" "$NAMESPACE_APP"
  wait_for_rollout deployment "${HELM_RELEASE}-orders-service" "$NAMESPACE_APP"
  wait_for_rollout deployment "${HELM_RELEASE}-billing-service" "$NAMESPACE_APP"
  wait_for_rollout deployment "${HELM_RELEASE}-notification-service" "$NAMESPACE_APP"
  wait_for_rollout deployment "${HELM_RELEASE}-analytics-service" "$NAMESPACE_APP"
  wait_for_rollout deployment "${HELM_RELEASE}-catalog-service" "$NAMESPACE_APP"
  wait_for_rollout deployment grafana "$NAMESPACE_OBS"
  wait_for_rollout statefulset prometheus "$NAMESPACE_OBS"
  wait_for_rollout statefulset redis "$NAMESPACE_DATA"
  log "Core platform workloads are healthy."
}

wait_for_ingress_hostname() {
  local ingress_name="$1"
  local namespace="$2"
  local timeout_seconds="$3"
  local elapsed=0
  local hostname=""

  while (( elapsed < timeout_seconds )); do
    hostname="$(kubectl get ingress "$ingress_name" -n "$namespace" -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)"
    if [[ -n "$hostname" ]]; then
      printf '%s\n' "$hostname"
      return
    fi
    sleep 10
    elapsed=$((elapsed + 10))
  done

  die "ingress ${namespace}/${ingress_name} did not receive an ALB hostname within ${timeout_seconds}s."
}

finalize_public_dns() {
  section "Finalize ALB Route53 Aliases"
  local gateway_ingress_name="${HELM_RELEASE}-gateway-service-ingress"
  local grafana_ingress_name="grafana"

  local gateway_alb
  local grafana_alb
  gateway_alb="$(wait_for_ingress_hostname "$gateway_ingress_name" "$NAMESPACE_APP" "$INGRESS_TIMEOUT_SECONDS")"
  grafana_alb="$(wait_for_ingress_hostname "$grafana_ingress_name" "$NAMESPACE_OBS" "$INGRESS_TIMEOUT_SECONDS")"

  log "Gateway ALB hostname: $gateway_alb"
  log "Grafana ALB hostname: $grafana_alb"

  AUTO_APPROVE="$AUTO_APPROVE" \
  AWS_REGION="$AWS_REGION" \
  RELEASE_NAME="$HELM_RELEASE" \
  TF_VARS_FILE="$TF_VARS_FILE" \
  GATEWAY_NAMESPACE="$NAMESPACE_APP" \
  GRAFANA_NAMESPACE="$NAMESPACE_OBS" \
  "$ROOT_DIR/scripts/finalize-alb-dns.sh"
}

deploy_ui() {
  if [[ "$SKIP_UI_DEPLOY" == "true" ]]; then
    section "Skip UI Deployment"
    log "Skipping UI build and deploy because SKIP_UI_DEPLOY=true."
    return
  fi

  section "Build And Deploy UI"
  TF_DIR="$TF_DIR" \
  WEBAPP_DIR="$WEBAPP_DIR" \
  SKIP_CLOUDFRONT_INVALIDATION="$SKIP_CLOUDFRONT_INVALIDATION" \
  "$ROOT_DIR/scripts/deploy-ui.sh"
}

print_summary() {
  section "Deployment Summary"
  local tf_output_json
  local gateway_host
  local grafana_host
  local ui_url
  local ui_bucket

  tf_output_json="$(terraform -chdir="$TF_DIR" output -json)"
  gateway_host="$(jq -r '.gateway_ingress_host.value // empty' <<<"$tf_output_json")"
  grafana_host="$(jq -r '.grafana_ingress_host.value // empty' <<<"$tf_output_json")"
  ui_url="$(jq -r '.ui_custom_url.value // empty' <<<"$tf_output_json")"
  ui_bucket="$(jq -r '.ui_bucket_name.value // empty' <<<"$tf_output_json")"

  log "Image tag deployed: $IMAGE_TAG"
  [[ -n "$gateway_host" ]] && log "Gateway URL: https://${gateway_host}"
  [[ -n "$grafana_host" ]] && log "Grafana URL: https://${grafana_host}"
  [[ -n "$ui_url" ]] && log "UI URL: $ui_url"
  [[ -n "$ui_bucket" ]] && log "UI bucket: s3://${ui_bucket}"

  printf '\nUseful follow-up checks:\n'
  printf '  kubectl get pods -A\n'
  printf '  kubectl get ingress -A\n'
  printf '  terraform -chdir=%q output\n' "$TF_DIR"
  if [[ -n "$gateway_host" ]]; then
    printf '  curl -i https://%s/actuator/health\n' "$gateway_host"
  fi
  if [[ -n "$ui_url" ]]; then
    printf '  curl -I %s\n' "$ui_url"
  fi
}

main() {
  local tf_vars_path
  tf_vars_path="$(resolve_tf_vars_path)"

  warn_namespace_override_limitations
  ensure_tooling
  ensure_aws_session

  section "Restore Pending-Deletion Secrets"
  "$ROOT_DIR/scripts/restore-secrets-if-pending-deletion.sh"

  ensure_tfvars "$tf_vars_path"
  run_terraform_apply "$tf_vars_path"
  update_kubeconfig
  wait_for_cluster
  bootstrap_cluster
  build_and_push_images
  render_prod_values
  validate_deploy_inputs
  install_or_upgrade_release
  wait_for_workloads
  finalize_public_dns
  deploy_ui
  print_summary
}

main "$@"
