apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orders-service.fullname" . }}-config
  namespace: {{ include "acmecorp-platform.namespace.app" . }}
  labels:
    {{- include "orders-service.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.global.aurora.host | quote }}
  DB_PORT: {{ .Values.global.aurora.port | quote }}
  DB_NAME: {{ .Values.global.aurora.database | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
  RABBITMQ_HOST: {{ .Values.global.mq.host | quote }}
  RABBITMQ_PORT: {{ .Values.global.mq.port | quote }}
